### ISSUE TITLE
AttributeError: 'pysam.libcalignedsegment.AlignedSegment' object has no attribute 'is_forward'

### ISSUE THREAD

**Issue by calvarez3280** [fothia/improve-RRBS#1]
Hello, 

I'm trying to analyze some RRBS data from human samples, but I'm constantly getting the following errors: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/iRRBS/run_irrbs.py", line 32, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/iRRBS/run_irrbs.py", line 27, in main
    pipeline.msp1_clip()
  File "/usr/local/lib/python3.8/dist-packages/iRRBS/irrbs_pipeline.py", line 128, in msp1_clip
    if read.is_forward:
AttributeError: 'pysam.libcalignedsegment.AlignedSegment' object has no attribute 'is_forward'
```
My major concern is the last line "AttributeError: 'pysam.libcalignedsegment.AlignedSegment' object has no attribute 'is_forward'", but I can't understand why pysam cannot recognized any of the forward reads. 

No output .bam is generated but the .log file contains the following info: 

```
Number of unique MspI reads:
14407
Number of MspI reads:
39930
Number of all reads:
28974472

```
Any idea of what might be happening?

Thank you.

**Comment by fothia** [comment]
The error you're encountering (AttributeError: 'pysam.libcalignedsegment.AlignedSegment' object has no attribute 'is_forward') is likely due to using a version of pysam older than 0.19.0. The is_forward attribute was introduced in pysam version 0.19.0, so if you're using an earlier version, it won’t be available, which is causing the error.
To confirm, please share the version of pysam you're currently using.
If you're using a version earlier than 0.19.0, I would recommend upgrading pysam to 0.19.0 or higher to resolve this issue.

**Comment by calvarez3280** [comment]
Hello,
Thanks for your answer. Indeed, my pysam version seems to be older: 
`pysam in /usr/local/lib/python3.8/dist-packages (0.17.0)`
I will update it to check if the issue gets resolved. Thank you.

**Comment by calvarez3280** [comment]
Hello,
The error related with the 'is_forward' attribute got solved. However, I have now a new issue: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/iRRBS/run_irrbs.py", line 32, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/iRRBS/run_irrbs.py", line 27, in main
    pipeline.msp1_clip()
  File "/usr/local/lib/python3.8/dist-packages/iRRBS/irrbs_pipeline.py", line 132, in msp1_clip
    read.set_tags([('NM', read.tags[0][1]),('MD', read.tags[1][1]),
IndexError: list index out of range
```
Some online sites suggest it might be a situation related with the python version used, mine is 3.8. Do you think that is the case? 

Thank you.

**Comment by fothia** [comment]
I see two potential reasons for the error:
   - Some of your reads might be too short, for example, with a read length below 5. Short reads may not generate the expected tags, leading to the "index out of range" issue when the pipeline tries to access tags that aren't present.
   - BitMapperBS might use different tags than Bismark. Since Improve-RRBS was not tested with BAM files generated by BitMapperBS, it's possible that this difference in tagging conventions is causing the error. Could you provide a copy of a sample mapped read along with its SAM flags? That would help diagnose the issue further.

Let me know if this helps clarify the issue!
I'm grateful for these valuable insights, and I will incorporate them into a future version of the tool to improve compatibility and handle these cases more robustly. Thank you for your input!

**Comment by calvarez3280** [comment]
Hello, 
Thanks to you again for the reply and the clear explanation of the potential issues associated to our data. 
Do you have an email where I can send an example of a subset of our .bam files generated by bitMapperBS, along with the corresponding SAM flags?.

**Comment by fothia** [comment]
Hello,
you can send me the sample file to ***@***.***
Abel

calvarez3280 ***@***.***> ezt írta (időpont: 2024. szept.
12., Cs, 15:43):

**Comment by fothia** [comment]
You can now see my email address on my profile.

**Comment by fothia** [comment]
Hello,
I have updated the iRRBS tool, and it is now compatible with bitMapperBS and MethylDackel. You can install it via pip or directly from the source on GitHub.

**Comment by calvarez3280** [comment]
Thank you for the updated version. I will test it right away!
